
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package esercitazione5;

/** CUP generated interface containing symbol constants. */
public interface sym {
  /* terminals */
  public static final int CHAR_CONST = 55;
  public static final int POW = 52;
  public static final int CHAR = 17;
  public static final int GE = 45;
  public static final int UMINUS = 59;
  public static final int INTEGER_CONST = 56;
  public static final int SEMI = 36;
  public static final int OTHERWISEDO = 8;
  public static final int INT = 13;
  public static final int OUT = 20;
  public static final int RBRAC = 33;
  public static final int MINUS = 49;
  public static final int FOR = 21;
  public static final int WRITE = 39;
  public static final int NOT = 28;
  public static final int AND = 26;
  public static final int LT = 41;
  public static final int RPAR = 31;
  public static final int OR = 27;
  public static final int COMMA = 35;
  public static final int BOOL = 16;
  public static final int DOTLOOP = 6;
  public static final int DIV = 51;
  public static final int GODOTWHEN = 5;
  public static final int PLUS = 48;
  public static final int LOOP = 23;
  public static final int ASSIGN = 47;
  public static final int WRITELN = 40;
  public static final int MAIN = 2;
  public static final int IF = 9;
  public static final int ID = 54;
  public static final int DOT = 3;
  public static final int LE = 44;
  public static final int EOF = 0;
  public static final int RETURN = 29;
  public static final int TRUE = 24;
  public static final int error = 1;
  public static final int PIPE = 37;
  public static final int VOID = 18;
  public static final int EQ = 46;
  public static final int TIMES = 50;
  public static final int COLON = 34;
  public static final int ELSE = 11;
  public static final int READ = 38;
  public static final int TO = 22;
  public static final int WHILE = 12;
  public static final int STR_CONCAT = 53;
  public static final int LET = 4;
  public static final int FLOAT = 14;
  public static final int THEN = 60;
  public static final int REAL_CONST = 58;
  public static final int NE = 43;
  public static final int LPAR = 30;
  public static final int STRING = 15;
  public static final int DEF = 19;
  public static final int LBRAC = 32;
  public static final int FALSE = 25;
  public static final int STRING_CONST = 57;
  public static final int GT = 42;
  public static final int VAR = 10;
  public static final int DOTWHEN = 7;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "MAIN",
  "DOT",
  "LET",
  "GODOTWHEN",
  "DOTLOOP",
  "DOTWHEN",
  "OTHERWISEDO",
  "IF",
  "VAR",
  "ELSE",
  "WHILE",
  "INT",
  "FLOAT",
  "STRING",
  "BOOL",
  "CHAR",
  "VOID",
  "DEF",
  "OUT",
  "FOR",
  "TO",
  "LOOP",
  "TRUE",
  "FALSE",
  "AND",
  "OR",
  "NOT",
  "RETURN",
  "LPAR",
  "RPAR",
  "LBRAC",
  "RBRAC",
  "COLON",
  "COMMA",
  "SEMI",
  "PIPE",
  "READ",
  "WRITE",
  "WRITELN",
  "LT",
  "GT",
  "NE",
  "LE",
  "GE",
  "EQ",
  "ASSIGN",
  "PLUS",
  "MINUS",
  "TIMES",
  "DIV",
  "POW",
  "STR_CONCAT",
  "ID",
  "CHAR_CONST",
  "INTEGER_CONST",
  "STRING_CONST",
  "REAL_CONST",
  "UMINUS",
  "THEN"
  };
}

